Добавляет наставника
htmlacademy-htmlcss/2011605-sedona-33 pull request #1
Opened 2022-01-19 11:42 UTC by VeronikaaaP

2022-01-19 12:09 UTC, Pakistanka requested changes

2022-01-19 12:09 UTC, Pakistanka commented on Readme.md
> +* Наставник: `Анастасия Полозова`.
Необходимо добавить ссылку на наставника также, как ты добавила ссылку на себя

2022-01-19 12:24 UTC, VeronikaaaP commented on Readme.md
> +* Наставник: `Анастасия Полозова`.
Добавила

2022-01-24 15:30 UTC, Pakistanka approved these changes
Поехало форматирование разметки. Сделай
если у тебя МАС - Shift Command P -> Format Document
Use Shift + Alt + f or Shift + Alt + F on windows

<a class="button" - грубая ошибка. Тег а - это ссылка, а button - это кнопка. Нельзя ссылкам давать класс кнопка и наоборот.

Поправь пожалуйста по всему сайту

2022-01-24 15:30 UTC, Pakistanka commented on index.html
> +      <a class="button" href="https://www.youtube.com/c/HTMLAcademyRUS">
`<a class="button"` - грубая ошибка. Тег а - это ссылка, а button - это кнопка. Нельзя ссылкам давать класс кнопка и наоборот.

Поправь пожалуйста по всему сайту

2022-01-24 15:30 UTC, Pakistanka commented on index.html
> + <header class="page-header">
Поехало форматирование разметки. Сделай
если у тебя МАС - Shift Command P -> Format Document
Use Shift + Alt + f or Shift + Alt + F on windows

2022-01-24 15:30 UTC, merged

2022-01-25 13:15 UTC, VeronikaaaP commented on index.html
> +      <a class="button" href="https://www.youtube.com/c/HTMLAcademyRUS">
а почему тогда у нас в примере, который рассматривали на лайве соц. сети в футере были оформлены таким же образом? <a class="botton>". Делала эту часть по примеру

2022-01-25 13:16 UTC, VeronikaaaP commented on index.html
> + <header class="page-header">
поправила, спасибо