Добавляет базовую стилизацию страниц
htmlacademy-htmlcss/2011605-sedona-33 pull request #3
Opened 2022-02-05 13:00 UTC by VeronikaaaP

2022-02-06 08:32 UTC, Pakistanka requested changes
1. Самое главное - у всех ссылок (`<a href="#"></a>`) убрать `class="button"`. Я не приму: потому что это грубая ошибка

2022-02-06 08:32 UTC, Pakistanka commented on catalog.html
> +                    <a class="navigation-link button" href="#">Хочу сюда!</a>
Опять повторяешь ошибку: в ссылках мы не можем писать класс button! Это нужно исправить

2022-02-06 08:32 UTC, Pakistanka commented on catalog.html
> +                    <a class="product-card-button-more button" href="#">подробнее</a>
На ссылках не может быть класса button

2022-02-06 08:32 UTC, Pakistanka commented on catalog.html
>                      <a class="product-card-button button" href="#">В избранное</a>
аналогично предыдущему комментарию

2022-02-06 08:32 UTC, Pakistanka commented on styles/styles.css
> +    color: black;
Мы стараемся по минимуму использовать буквенное обозначение цветов. Есть hex code #000000;

Поправь все цвета в разметке

2022-02-06 09:24 UTC, VeronikaaaP commented on catalog.html
> +                    <a class="navigation-link button" href="#">Хочу сюда!</a>
@Pakistanka скажи, а в каких социальных сетях ты отвечаешь? у меня есть вопросы по проекту, писала на фейсбуке, но там ты не ответила. где тогда я могу задать свои вопросы?

2022-02-07 15:48 UTC, Pakistanka approved these changes

2022-02-07 15:48 UTC, merged